export const studentMockData = [
  {
    name: "John Doe",
    rollNumber: "101",
    grade: "12-A",
    contact: "555-1001",
    email: "john.doe@example.com",
    attendance: "94%",
    performance: "A",
    address: "221B Baker Street, London",
  },
  {
    name: "Jane Smith",
    rollNumber: "102",
    grade: "10-B",
    contact: "555-1002",
    email: "jane.smith@example.com",
    attendance: "88%",
    performance: "B+",
    address: "14 Park Avenue, New York",
  },
  {
    name: "Sam Brown",
    rollNumber: "103",
    grade: "6-A",
    contact: "555-1003",
    email: "sam.brown@example.com",
    attendance: "91%",
    performance: "A-",
    address: "3 MG Road, Bengaluru",
  },
  {
    name: "Lisa White",
    rollNumber: "104",
    grade: "5-C",
    contact: "555-1004",
    email: "lisa.white@example.com",
    attendance: "86%",
    performance: "B",
    address: "45 Green Street, Delhi",
  },
  {
    name: "Aarav Patel",
    rollNumber: "105",
    grade: "10-A",
    contact: "555-1005",
    email: "aarav.patel@example.com",
    attendance: "95%",
    performance: "A+",
    address: "12 Patel Nagar, Ahmedabad",
  },
  {
    name: "Meera Nair",
    rollNumber: "106",
    grade: "9-B",
    contact: "555-1006",
    email: "meera.nair@example.com",
    attendance: "89%",
    performance: "B+",
    address: "89 MG Road, Kochi",
  },
  {
    name: "Rohan Sharma",
    rollNumber: "107",
    grade: "11-C",
    contact: "555-1007",
    email: "rohan.sharma@example.com",
    attendance: "92%",
    performance: "A",
    address: "56 Sector 15, Gurugram",
  },
  {
    name: "Anika Verma",
    rollNumber: "108",
    grade: "7-A",
    contact: "555-1008",
    email: "anika.verma@example.com",
    attendance: "90%",
    performance: "A-",
    address: "9 Tagore Street, Jaipur",
  },
  {
    name: "David Lee",
    rollNumber: "109",
    grade: "8-C",
    contact: "555-1009",
    email: "david.lee@example.com",
    attendance: "85%",
    performance: "B",
    address: "77 Main Street, Singapore",
  },
  {
    name: "Sophia Kim",
    rollNumber: "110",
    grade: "12-B",
    contact: "555-1010",
    email: "sophia.kim@example.com",
    attendance: "97%",
    performance: "A+",
    address: "10 River Valley, Seoul",
  },
  {
    name: "Kabir Singh",
    rollNumber: "111",
    grade: "6-B",
    contact: "555-1011",
    email: "kabir.singh@example.com",
    attendance: "83%",
    performance: "B-",
    address: "23 Model Town, Ludhiana",
  },
  {
    name: "Emma Johnson",
    rollNumber: "112",
    grade: "9-C",
    contact: "555-1012",
    email: "emma.johnson@example.com",
    attendance: "90%",
    performance: "A-",
    address: "15 Wellington Street, Toronto",
  },
  {
    name: "Noah Wilson",
    rollNumber: "113",
    grade: "5-A",
    contact: "555-1013",
    email: "noah.wilson@example.com",
    attendance: "87%",
    performance: "B",
    address: "32 Cherry Lane, Sydney",
  },
  {
    name: "Olivia Davis",
    rollNumber: "114",
    grade: "10-A",
    contact: "555-1014",
    email: "olivia.davis@example.com",
    attendance: "96%",
    performance: "A+",
    address: "9 Residency Road, Pune",
  },
  {
    name: "Liam Brown",
    rollNumber: "115",
    grade: "11-B",
    contact: "555-1015",
    email: "liam.brown@example.com",
    attendance: "88%",
    performance: "B+",
    address: "101 Orchard Avenue, Dublin",
  },
  {
    name: "Ethan Jones",
    rollNumber: "116",
    grade: "7-C",
    contact: "555-1016",
    email: "ethan.jones@example.com",
    attendance: "84%",
    performance: "B",
    address: "88 Palm Street, Goa",
  },
  {
    name: "Aisha Khan",
    rollNumber: "117",
    grade: "8-B",
    contact: "555-1017",
    email: "aisha.khan@example.com",
    attendance: "91%",
    performance: "A-",
    address: "25 Hill Road, Mumbai",
  },
  {
    name: "Ryan Clark",
    rollNumber: "118",
    grade: "12-C",
    contact: "555-1018",
    email: "ryan.clark@example.com",
    attendance: "89%",
    performance: "B+",
    address: "12 Baker Avenue, London",
  },
  {
    name: "Nina George",
    rollNumber: "119",
    grade: "6-A",
    contact: "555-1019",
    email: "nina.george@example.com",
    attendance: "85%",
    performance: "B",
    address: "44 Temple Road, Chennai",
  },
  {
    name: "Arjun Mehta",
    rollNumber: "120",
    grade: "9-A",
    contact: "555-1020",
    email: "arjun.mehta@example.com",
    attendance: "93%",
    performance: "A",
    address: "21 Nehru Place, Delhi",
  },
  {
    name: "Priya Iyer",
    rollNumber: "121",
    grade: "10-C",
    contact: "555-1021",
    email: "priya.iyer@example.com",
    attendance: "90%",
    performance: "A-",
    address: "76 Race Course, Coimbatore",
  },
  {
    name: "Daniel Kim",
    rollNumber: "122",
    grade: "7-B",
    contact: "555-1022",
    email: "daniel.kim@example.com",
    attendance: "86%",
    performance: "B",
    address: "8 Harbour Street, Busan",
  },
  {
    name: "Sara Ali",
    rollNumber: "123",
    grade: "5-B",
    contact: "555-1023",
    email: "sara.ali@example.com",
    attendance: "92%",
    performance: "A",
    address: "63 MG Road, Indore",
  },
  {
    name: "Henry Adams",
    rollNumber: "124",
    grade: "11-A",
    contact: "555-1024",
    email: "henry.adams@example.com",
    attendance: "89%",
    performance: "B+",
    address: "7 Hillview Lane, London",
  },
  {
    name: "Isabella Lopez",
    rollNumber: "125",
    grade: "8-A",
    contact: "555-1025",
    email: "isabella.lopez@example.com",
    attendance: "95%",
    performance: "A+",
    address: "90 Maple Drive, Madrid",
  },
  {
    name: "Karan Gupta",
    rollNumber: "126",
    grade: "9-B",
    contact: "555-1026",
    email: "karan.gupta@example.com",
    attendance: "87%",
    performance: "B",
    address: "13 Civil Lines, Kanpur",
  },
  {
    name: "Mia Thomas",
    rollNumber: "127",
    grade: "6-C",
    contact: "555-1027",
    email: "mia.thomas@example.com",
    attendance: "90%",
    performance: "A-",
    address: "33 Lakeview Road, Kochi",
  },
  {
    name: "Lucas Green",
    rollNumber: "128",
    grade: "12-A",
    contact: "555-1028",
    email: "lucas.green@example.com",
    attendance: "94%",
    performance: "A",
    address: "5 Sunset Blvd, California",
  },
  {
    name: "Aditi Joshi",
    rollNumber: "129",
    grade: "10-B",
    contact: "555-1029",
    email: "aditi.joshi@example.com",
    attendance: "88%",
    performance: "B+",
    address: "22 Law College Road, Pune",
  },
  {
    name: "Jacob Martin",
    rollNumber: "130",
    grade: "11-C",
    contact: "555-1030",
    email: "jacob.martin@example.com",
    attendance: "85%",
    performance: "B",
    address: "11 Whitefield, Bengaluru",
  },
];